// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Url struct {
	ID            int64
	OriginalUrl   string
	Code          string
	CreatedAt     time.Time
	AccessedCount int64
	LastAccessed  sql.NullTime
}
