// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_db

import (
	"database/sql"
)

type Url struct {
	ID            int64
	OriginalUrl   string
	Code          string
	CreatedAt     sql.NullTime
	AccessedCount sql.NullInt64
	LastAccessed  sql.NullTime
}
